### ISSUE TITLE
The program can't recognize the "spec_id".

### ISSUE THREAD

**Issue by blackbear10000** [certusone/chainlink-exporter#2]
Hi. Recently, I found the program can't recognize the "spec_id". Would you like to check it. Thanks.

```
{"level":"info","ts":1584082510.0858984,"caller":"chainlink_exporter/monitor.go:380","msg":"received request","height":9661685,"requester":"0xc89c4ed8f52Bb17314022f6c0dCB26210C905C97","request_id":"i2i780oA0ZdvPKES22UQpc4cJglkPxik/gwYZtwwO4M=","spec_id":"\n\r\ufffd\ufffd\ufffd\ufffdJ\ufffd\ufffdV\ufffdWg\ufffd\u001d\ufffd\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"}
{"level":"info","ts":1584082569.7957022,"caller":"chainlink_exporter/aggregator.go:116","msg":"job fulfilled","height":9661688,"requester":"0xc89c4ed8f52Bb17314022f6c0dCB26210C905C97","request_id":"i2i780oA0ZdvPKES22UQpc4cJglkPxik/gwYZtwwO4M=","spec_id":"\n\r\ufffd\ufffd\ufffd\ufffdJ\ufffd\ufffdV\ufffdWg\ufffd\u001d\ufffd\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","request_height":9661685}
panic: label value "\n\r\xfd\xf3\xe4\xe2J\x87\x94V\xb8Wg\x81\x1d\xd5\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" is not valid UTF-8

goroutine 1277 [running]:
github.com/prometheus/client_golang/prometheus.(*HistogramVec).WithLabelValues(0xc00000e028, 0xc0002ea190, 0x1, 0x1, 0xc0003ac080, 0x20)
	/Users/yuanshuai/Documents/WorkSpace/go/pkg/mod/github.com/prometheus/client_golang@v1.3.0/prometheus/histogram.go:439 +0xdf
main.(*Monitor).HandleFulfillment(0xc00015a0f0, 0xc000cbcb60, 0xc000b4c420)
	/Users/yuanshuai/Documents/WorkSpace/go/src/chainlink_exporter/cmd/chainlink_exporter/monitor.go:422 +0x114
main.(*AggregatorMonitor).handleFulfillment(0xc000c62f50, 0xc000cbcb60)
	/Users/yuanshuai/Documents/WorkSpace/go/src/chainlink_exporter/cmd/chainlink_exporter/aggregator.go:121 +0x7ff
main.(*AggregatorMonitor).Monitor.func1(0xc000c62f50)
	/Users/yuanshuai/Documents/WorkSpace/go/src/chainlink_exporter/cmd/chainlink_exporter/aggregator.go:66 +0x1a6
main.(*AggregatorMonitor).Monitor(0xc000c62f50)
	/Users/yuanshuai/Documents/WorkSpace/go/src/chainlink_exporter/cmd/chainlink_exporter/aggregator.go:69 +0x214
created by main.(*Monitor).handleRequest
	/Users/yuanshuai/Documents/WorkSpace/go/src/chainlink_exporter/cmd/chainlink_exporter/monitor.go:409 +0x7b3
```

**Comment by blackbear10000** [comment]
I found a special situation.

```
var specid = []byte{217, 47, 206, 91, 69, 139, 74, 6, 146, 24, 134, 160, 50, 84, 169, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
zap.L().Info("Test: ", zap.ByteString("specid: ", specid[:]))
```

The result is :
`{"level":"info","ts":1584098268.591261,"caller":"cmd/trans.go:26","msg":"Test: ","specid: ":"\ufffd/\ufffd[E\ufffdJ\u0006\ufffd\u0018\ufffd\ufffd2T\ufffd\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"}`

**Comment by hendrikhofstadt** [comment]
Thanks, will work on a fix

**Comment by blackbear10000** [comment]
I found a rule that can be expressed by code. It works. But I don't know the reason.

```
func getRealID(spec_id []byte) string {
	var result string = ""
	if isUtf8(spec_id) == false {
		for n, value := range spec_id[:] {
			result = result + fmt.Sprintf("%02x", value)
			if n == 15 {
				break
			}
		}
	} else {
		result = fmt.Sprintf("%s", string(spec_id[:]))
	}

	return result
}
```

**Comment by hendrikhofstadt** [comment]
Should be fixed by https://github.com/certusone/chainlink_exporter/commit/7a831a9a044bee4bc214d6e5ef67403336bdfef7 in v1.0.5
